// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// build_forest_predict_cpp
NumericMatrix build_forest_predict_cpp(NumericMatrix trainX, NumericMatrix trainY, int n_tree, int m_feature, int min_leaf, NumericMatrix testX, int nCores);
RcppExport SEXP _CompositionalRF_build_forest_predict_cpp(SEXP trainXSEXP, SEXP trainYSEXP, SEXP n_treeSEXP, SEXP m_featureSEXP, SEXP min_leafSEXP, SEXP testXSEXP, SEXP nCoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type trainX(trainXSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type trainY(trainYSEXP);
    Rcpp::traits::input_parameter< int >::type n_tree(n_treeSEXP);
    Rcpp::traits::input_parameter< int >::type m_feature(m_featureSEXP);
    Rcpp::traits::input_parameter< int >::type min_leaf(min_leafSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type testX(testXSEXP);
    Rcpp::traits::input_parameter< int >::type nCores(nCoresSEXP);
    rcpp_result_gen = Rcpp::wrap(build_forest_predict_cpp(trainX, trainY, n_tree, m_feature, min_leaf, testX, nCores));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CompositionalRF_build_forest_predict_cpp", (DL_FUNC) &_CompositionalRF_build_forest_predict_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_CompositionalRF(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
