comp.rf <- function(xnew = x, y, x, type = "alr", ntrees, nfeatures, minleaf,
                    ncores = 0) {
  
  if ( type == "alr" )  y <- Compositional::alr(y)
  # est <- MultivariateRandomForest::build_forest_predict(trainX = x,
  #                                                      trainY = y,
  #   n_tree = ntrees, m_feature = nfeatures, min_leaf = minleaf, testX = xnew)
  est <- .build_forest_predict_cpp(trainX = x, trainY = y,
                                                   n_tree = ntrees,
                                                   m_feature = nfeatures,
                                                   min_leaf = minleaf,
                                                   testX = xnew,
                                                   nCores = ncores)
  Compositional::alrinv(est)
}


# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.build_forest_predict_cpp <- function(trainX, trainY, n_tree, m_feature, min_leaf, testX, nCores = 0L) {
  .Call(`_CompositionalRF_build_forest_predict_cpp`, trainX, trainY, n_tree, m_feature, min_leaf, testX, nCores)
}

